### ISSUE TITLE
Problems with first login

### ISSUE THREAD

**Issue by jakob42** [hooram/ownphotos#36] opened 2018-09-07 09:04 UTC
Hi,

I deployed ownphotos with the following docker-compose.yml, trying to replicate the docker settings from the readme. But I cannot login with the credentials from the environment, I get the error "Invalid token specified". The labels are for traefik instead of nginx, but I don't think thats a problem, I can access both backend and frontend without any problems.

```
version: '2'

services:
  ownphotos:
    image: ownphotos
    volumes:
      - /srv/ownphotos/data:/data
      - /srv/ownphotos/media:/code/media
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=true"
      - "traefik.front.frontend.rule=Host:pics.example.com"
      - "traefik.front.port=5000"
      - "traefik.back.frontend.rule=Host:backend.pics.example.com"
      - "traefik.back.port=80"
    environment:
      - SECRET_KEY=asdf
      - ADMIN_EMAIL=me@example.com
      - ADMIN_USERNAME=myuser
      - ADMIN_PASSWORD=mypass
      - DEBUG=false
      - DB_BACKEND=postgresql
      - DB_NAME=ownphotos
      - DB_USER=ownphotos
      - DB_PASS=dbpass
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MAPBOX_API_KEY=CHANGE_ME
      - BACKEND_HOST=backend.pics.example.com
    links:
      - "db"
      - "redis"

  db:
    image: postgres
    environment:
      POSTGRES_DB: ownphotos
      POSTGRES_USER: ownphotos
      POSTGRES_PASSWORD: dbpass
    volumes:
      - /srv/ownphotos/db:/var/lib/postgresql/data

  redis:
    image: redis
```

I cannot find anything in the log, even with `DEBUG=true`. Any idea where to look further?

Thanks,
Jakob

**Comment by jakob42** [comment] 2018-09-10 08:42
I didn't add a mapbox api key, I hope thats not a problem for a first test

**Comment by dvarum12** [comment] 2018-09-11 06:34
I have gotten my to work with the master branch, maybe that can help you to figure out what is wrong, however I cannot get it working with Nginx as a reverse proxy.`
[ownphotos.zip](https://github.com/hooram/ownphotos/files/2369597/ownphotos.zip)

```
version: '3'

services:
    ownphotos:
        #image: nhooram/ownphotos:0.1
        image: hooram/ownphotos:master
        #image: hooram/ownphotos:dev
        links:
        - ownphotos-db
        - ownphotos-redis

        volumes:
        - ownphotos-data:/data
        - ownphotos-metadata:/code/media
        
        environment:
        - SECRET_KEY=dfUEAn47w47nYkEByy49zsCuJHyLSwWL
        - ADMIN_EMAIL=ownphotos@varum.dk
        - ADMIN_USERNAME=dennis
        - ADMIN_PASSWORD=tester1212
        - DEBUG=false
        - DB_BACKEND=postgresql
        - DB_NAME=ownphotos
        - DB_USER=ownphotos
        - DB_PASS=9gVjyaab9HfKLZnM
        - DB_HOST=ownphotos-db
        - DB_PORT=5432
        - REDIS_HOST=ownphotos-redis
        - REDIS_PORT=6379
        - MAPBOX_API_KEY=pk.eyJ1IjoibXVoYWgiLCJhIjoiY2pqcGRmZjdjMXV0ODNrbzE0Y3IwNHlieiJ9.qIorLl7KBRKLrCR-pFxLXg
        #- BACKEND_HOST=ownphotos-api.local:8080
        - BACKEND_HOST=localhost:8000

        ports:
        - 8000:80
        - 3000:3000
        - 5000:5000

        
    ownphotos-db:
        image: postgres:alpine
        container_name: postgres
        restart: always
        
        volumes:
         - ownphotos-db:/var/lib/postgresql/data
        
        environment:
        - POSTGRES_DB=ownphotos
        - POSTGRES_USER=ownphotos
        - POSTGRES_PASSWORD=9gVjyaab9HfKLZnM

        
    ownphotos-redis:
        image: redis:alpine
        container_name: redis
        volumes:
        - ownphotos-redis:/data

        
#    nginx:
#        image: nginx:latest
#        restart: always

#        links:
#        - ownphotos

#        volumes:
#        - ./nginx.conf:/etc/nginx/nginx.conf:ro

#        ports:
#        - 8080:80
    
volumes:
    ownphotos-data:
    ownphotos-metadata:
    ownphotos-db:
    ownphotos-redis:
``

**Comment by dvarum12** [comment] 2018-09-11 06:42
I go my working with the master branch maybe that can help you find out what was wrong. I am still trying to make it work with Nginx as a reverse proxy.
[ownphotos.zip](https://github.com/hooram/ownphotos/files/2369622/ownphotos.zip)

```
version: '3'

services:
    ownphotos:
        #image: nhooram/ownphotos:0.1
        image: hooram/ownphotos:master
        #image: hooram/ownphotos:dev
        links:
        - ownphotos-db
        - ownphotos-redis

        volumes:
        - ownphotos-data:/data
        - ownphotos-metadata:/code/media
        
        environment:
        - SECRET_KEY=SECRET_KEY
        - ADMIN_EMAIL=ownphotos@varum.dk
        - ADMIN_USERNAME=admin
        - ADMIN_PASSWORD=PASSWORD
        - DEBUG=false
        - DB_BACKEND=postgresql
        - DB_NAME=ownphotos
        - DB_USER=ownphotos
        - DB_PASS=PASSWORD
        - DB_HOST=ownphotos-db
        - DB_PORT=5432
        - REDIS_HOST=ownphotos-redis
        - REDIS_PORT=6379
        - MAPBOX_API_KEY=MAPBOX_API_KEY
        #- BACKEND_HOST=ownphotos-api.local:8080
        - BACKEND_HOST=localhost:8000

        ports:
        - 8000:80
        - 3000:3000
        - 5000:5000

        
    ownphotos-db:
        image: postgres:alpine
        container_name: postgres
        restart: always
        
        volumes:
         - ownphotos-db:/var/lib/postgresql/data
        
        environment:
        - POSTGRES_DB=ownphotos
        - POSTGRES_USER=ownphotos
        - POSTGRES_PASSWORD=PASSWORD

        
    ownphotos-redis:
        image: redis:alpine
        container_name: redis
        volumes:
        - ownphotos-redis:/data

        
#    nginx:
#        image: nginx:latest
#        restart: always

#        links:
#        - ownphotos

#        volumes:
#        - ./nginx.conf:/etc/nginx/nginx.conf:ro

#        ports:
#        - 8080:80
    
volumes:
    ownphotos-data:
    ownphotos-metadata:
    ownphotos-db:
    ownphotos-redis:
```

**Comment by jakob42** [comment] 2018-09-11 08:33
Strange, I tried both an image from master as well as v0.1, both didn't work. v0.1 had `e.response is undefined` as error instead. :(

**Comment by guysoft** [comment] 2018-11-23 19:07
Hey, same issue here, getting e.response is undefined
![screenshot_20181123_210702](https://user-images.githubusercontent.com/325670/48957795-be66a980-ef63-11e8-9324-008900e64821.png)

**Comment by guysoft** [comment] 2018-11-23 19:46
Ok, strange, I am getting different errors from chromium and firefox.
Chromium is on the left and firefox is on the right. Same server, same machine
![chrome_firefox](https://user-images.githubusercontent.com/325670/48958637-279ceb80-ef69-11e8-9673-87c85296d6e9.png)

Chromium:
e.response is undefined

Firefox:
Cannot read property 'status' of undefined

**Comment by hooram** [comment] 2018-11-24 11:31
Basically the issue is that on the front end code, the base URL to the backend server is written "changeme/api", and the configuration doesn't handle this properly. If you can run the front end separately and modify that bit (should be in apiclient.js), it should work.

**Comment by guysoft** [comment] 2018-11-24 16:36
@hooram
Hey,  in my setting it looks like its pulling from the right location, but I am getting 301 moved permenantly:

![screenshot_20181124_183201](https://user-images.githubusercontent.com/325670/48970639-66897a80-f017-11e8-9c9b-157654fa299c.png)

How would I separate the backend from the frontend? I see there is a docker-compose.yml in the repo, but it has ``build: .``, and i see you didn't publish it:

```
services:
  frontend:
    image: ownphotos-frontend
    ports:
      - 3000
build: .
```

**Comment by hooram** [comment] 2018-11-26 05:08
@guysoft 
It should be in the frontend repo, dev branch.

**Comment by guysoft** [comment] 2018-11-29 18:38
Ok, 
so 
1.  I am using [jwilder/nginx-proxy](https://github.com/jwilder/nginx-proxy) so I do have https on the backed side.
2. I warmly suggest you switch the default banch of ownphotos-frontend to ``dev`` if you want people to chekout and build that
3. I suggest you add an automated build to docker container to docker hub. It means evrey commit and fix you do will got right away to docker containers. I wil gladly help set it up for you, since if the container would be guysoft/ownphotos-frontend I think less people would find it.
4. When building ownphotos-frontend from dev branch I get:

```
Step 8/11 : RUN npm install && npm cache clean --force
 ---> Running in 85a57860f617
npm WARN deprecated react-router-redux@5.0.0-alpha.9: This project is no longer maintained.
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm WARN deprecated @types/redux@3.6.0: This is a stub types definition for Redux (https://github.com/reactjs/redux). Redux provides its own type de
finitions, so you don't need @types/redux installed!
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9
ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js

> semantic-ui@2.4.2 install /usr/src/app/node_modules/semantic-ui
> gulp install


...
npm WARN reapop@1.2.0 requires a peer of redux@^2.0.0 || ^3.0.0 but none was installed.
npm WARN react-sortable-tree-theme-file-explorer@1.1.2 requires a peer of react-sortable-tree@^1.4.0 but none was installed.
npm WARN material-icons-react@1.0.4 requires a peer of react@~0.14.8 || ^15.0.0 but none was installed.
npm WARN material-icons-react@1.0.4 requires a peer of react-dom@~0.14.8 || ^15.0.0 but none was installed.
npm WARN bootstrap@4.1.3 requires a peer of popper.js@^1.14.3 but none was installed.
npm WARN eslint-config-react-app@2.1.0 requires a peer of eslint-plugin-jsx-a11y@^5.1.1 but none was installed.
npm ERR! Linux 4.16.0-2-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.14.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! semantic-ui@2.4.2 install: `gulp install`
npm ERR! Exit status 130
npm ERR! 
npm ERR! Failed at the semantic-ui@2.4.2 install script 'gulp install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the semantic-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs semantic-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls semantic-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
```

**Comment by hooram** [comment] 2018-11-30 02:15
@guysoft 
Hey, thanks. I changed the default branch on the frontend repo to dev. I know the deployment scripts and dockerfiles are not up to date. Did you get everything to work without Docker? I would gladly accept pull requests.

**Comment by guysoft** [comment] 2018-12-01 23:32
1. 
I didn't try to deploy without docker, because it requires a bunch of configuration for the postgresql, and reverse proxy to get https. Docker seems like the logical way to set it all up. And once I get it running it would be super easy to deploy.
2.
I would gladly PR, once I understand and fix what is wrong.
For a start, you can merge this:
https://github.com/hooram/ownphotos-frontend/pull/30
3.
There seems to be an issue with npm dependencies. . I don't know what is needed and what is not , so you will have to tell me which libraries can go to resolve, seems like removing semantic-ui fixes it:

```
+-- UNMET PEER DEPENDENCY popper.js@^1.14.3
+-- UNMET PEER DEPENDENCY react@16.6.3
+-- UNMET PEER DEPENDENCY react-dom@16.6.3
+-- react-scripts@1.1.5
| +-- eslint@4.10.0 
| | +-- chalk@2.4.1 
| | +-- debug@3.2.6 
| | | `-- ms@2.1.1 
| | +-- doctrine@2.1.0 
| | +-- js-yaml@3.12.0 
| | | `-- esprima@4.0.1 
| | `-- strip-ansi@4.0.0 
| |   `-- ansi-regex@3.0.0 
| +-- UNMET PEER DEPENDENCY eslint-plugin-jsx-a11y@5.1.1
| `-- eslint-plugin-react@7.4.0 
|   +-- doctrine@2.1.0 
|   `-- jsx-ast-utils@2.0.1 
+-- UNMET PEER DEPENDENCY react-sortable-tree@2.3.0
+-- UNMET PEER DEPENDENCY redux@4.0.1

```
4.
My current deployment:
At the moment I have an instance running on a docker container here:
https://pics.gnethomelinux.com:3000

which gives 

I get "Invalid Host header"
And I am not sure where its coming from.

It looks like the api is working, but the frontend is not.
The api is here:
https://pics.gnethomelinux.com/

**Comment by guysoft** [comment] 2018-12-15 22:14
Ok, I got it working!!

Basically you can do this now:

    wget https://raw.githubusercontent.com/guysoft/ownphotos-frontend/dev/docker-compose.yml
    sudo docker-compose up -d

Thats it, you have ownphotos ruining at http://localhost:3000, syncing images from /home/use/Pictures 
(These commands already work now and you can test this)

Running example at: http://ownphotos.gnethomelinux.com/ user: admin/admin

Please please please accept my PRs so this can be official. Otherwise I suggest we fork am maintain it.
(Also if there is a problem with my PRs please state clearly, so I know what to fix).

**Comment by erikhubers** [comment] 2018-12-16 21:28
> Ok, I got it working!!

I can confirm this fixes the issue (on my machine)

**Comment by guysoft** [comment] 2018-12-26 15:52
Yay, closing

**Closed by guysoft** 2018-12-26 15:52 UTC

**Comment by jakob42** [comment] 2019-01-06 11:45
Btw, thanks for solving this, worked for me as well

**Comment by phicha20224** [comment] 2021-01-08 15:58
> ×
> ←→1 of 2 errors on the page
> TypeError: Cannot read property '0' of undefined
> LoginPage.render
> http://localhost:3000/static/js/bundle.js:281455:52
>   281452 |     },
>   281453 |     __self: this
>   281454 |   },
> > 281455 |   this.props.errors.data.non_field_errors[0]
>          |                                          ^  281456 | ),
>   281457 | this.props.errors && this.props.errors.non_field_errors && __WEBPACK_IMPORTED_MODULE_0_react___default.a.createElement(
>   281458 |   __WEBPACK_IMPORTED_MODULE_2_semantic_ui_react__["u" /* Message */],
> View source
> ▶ 26 stack frames were collapsed.
> (anonymous function)
> src/app/src/actions/authActions.js:70
>   67 |         dispatch(push(from))
>   68 |       })
>   69 |       .catch((err) => {
> > 70 |         dispatch({type: "LOGIN_REJECTED", payload: err})
>   71 |       })
>   72 |   }
>   73 | }
> View compiled
> This screen is visible only in development. It will not appear if the app crashes in production.
> Open your browser’s developer console to further inspect this error.


I am sorry, but i  try to find way to login after installing using docker.
i run this 
wget https://raw.githubusercontent.com/guysoft/ownphotos-frontend/dev/docker-compose.yml
sudo docker-compose up -d

ssh  -L 3000:localhost:3000 root@192.168.53.xx


and on browser i open localhost:3000 i asked to put password and username but it show this up..
Please help. Thank you

**Comment by derneuere** [comment] 2021-01-08 16:51
Hey, ownphotos is no longer maintained. Here is a fork of ownphotos that is maintained: https://github.com/LibrePhotos/librephotos
If you're issue still persists, please open a new issue in the librephotos repository.
